
name: Main Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: install app dependencies
        working-directory: ./Wordle App
        run: flutter pub get

      # - name: Run tests
      #   working-directory: ./Wordle App
      #   run: flutter test

      - name: Build flutter web
        working-directory: ./Wordle App
        run: flutter build web

      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web/
