name: Main Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Phase
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./wordle

    steps:
      # Clones source code repo
      - name: checkout repo
        uses: actions/checkout@v4

      # Installs Flutter
      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      # Makes sure all Flutter dependancies are installed
      - name: install app dependencies
        run: flutter pub get

      # Runs Smoke Tests
      - name: run smoke tests
        run: flutter test

      # Builds Web App
      - name: build flutter web
        run: flutter build web

      # Uploads Build Artifacts
      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-assets
          path: ./wordle/build/web/
  
  deploy:
    name: Deploy Phase
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Downloads Build Artifacts
      - name: download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-assets
      
      # Deploys Web App
      - name: Web Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web-assets